### ISSUE TITLE
simgear static libraries

### ISSUE THREAD

**Issue by triconor** [geoffmcl/test-btg#2]
Thank you for you answer,

is in Windows (32)

the message in CMAke is:

looking for static SimGear libraries
Simgear SIMGEAR_CORE_LIBRARY_RELEASE SIMGEAR_CORE_LIBRARY_RELEASE-NOTFOUND
Simgear SIMGEAR_CORE_LIBRARY_DEBUG SIMGEAR_CORE_LIBRARY_DEBUG-NOTFOUND
found 
Simgear SIMGEAR_SCENE_LIBRARY_RELEASE SIMGEAR_SCENE_LIBRARY_RELEASE-NOTFOUND
Simgear SIMGEAR_SCENE_LIBRARY_DEBUG SIMGEAR_SCENE_LIBRARY_DEBUG-NOTFOUND
found 
CMake Error at CMakeModules/FindSimGear.cmake:174 (message):
  Cannot find SimGear libraries! (Forgot 'make install' for SimGear?) Compile
  & INSTALL SimGear before configuring FlightGear.  When using non-standard
  locations, use 'SIMGEAR_DIR' to configure the SimGear location.
Call Stack (most recent call first):
  CMakeLists.txt:153 (find_package)

although i put the ubication of libraries SIMGEAR_SCENE_LIBRARY_DEBUG,SIMGEAR_SCENE_LIBRARY_RELEASE,SIMGEAR_CORE_LIBRARY_DEBUG,SIMGEAR_CORE_LIBRARY_RELEASE

**Comment by geoffmcl** [comment]
Follow this topic in #1 ... closing this duplicate...
